// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Signals from "@preact/signals";
import * as JsxRuntime from "preact/jsx-runtime";

Signals.signal(0);

function App(props) {
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsxs("main", {
                      children: [
                        JsxRuntime.jsx("div", {
                              children: JsxRuntime.jsxs("ul", {
                                    children: [
                                      JsxRuntime.jsx("li", {
                                            children: "#ffffff",
                                            className: "flex flex-col items-center justify-end p-4 rounded-lg border border-white"
                                          }),
                                      JsxRuntime.jsx("li", {
                                            children: "#ffffff",
                                            className: "flex flex-col items-center justify-end p-4 rounded-lg border border-white"
                                          }),
                                      JsxRuntime.jsx("li", {
                                            children: "#ffffff",
                                            className: "flex flex-col items-center justify-end p-4 rounded-lg border border-white"
                                          }),
                                      JsxRuntime.jsx("li", {
                                            children: "#ffffff",
                                            className: "flex flex-col items-center justify-end p-4 rounded-lg border border-white"
                                          }),
                                      JsxRuntime.jsx("li", {
                                            children: "#ffffff",
                                            className: "flex flex-col items-center justify-end p-4 rounded-lg border border-white"
                                          })
                                    ],
                                    className: "h-full grid grid-cols-5 gap-4"
                                  }),
                              className: "color-list bg-gray-950/40 h-72 p-8"
                            }),
                        JsxRuntime.jsx("div", {
                              children: JsxRuntime.jsx("svg", {
                                    children: JsxRuntime.jsx("circle", {
                                          cx: "300",
                                          cy: "300",
                                          fill: "white",
                                          r: "300"
                                        }),
                                    viewBox: "0 0 600 600"
                                  }),
                              className: "color-wheel p-16"
                            }),
                        JsxRuntime.jsxs("div", {
                              children: [
                                JsxRuntime.jsx("button", {
                                      children: "Custom"
                                    }),
                                JsxRuntime.jsx("button", {
                                      children: "Monochromatic"
                                    }),
                                JsxRuntime.jsx("button", {
                                      children: "Analogous"
                                    }),
                                JsxRuntime.jsx("button", {
                                      children: "Complementary"
                                    }),
                                JsxRuntime.jsx("button", {
                                      children: "Split Complementary"
                                    }),
                                JsxRuntime.jsx("button", {
                                      children: "Triad"
                                    }),
                                JsxRuntime.jsx("button", {
                                      children: "Quads"
                                    })
                              ],
                              className: "flex flex-row justify-center gap-2"
                            })
                      ],
                      className: "flex flex-col flex-grow"
                    }),
                JsxRuntime.jsx("aside", {
                      children: JsxRuntime.jsxs("nav", {
                            children: [
                              JsxRuntime.jsx("button", {
                                    children: "inspector",
                                    value: "properties"
                                  }),
                              JsxRuntime.jsx("button", {
                                    children: "palettes",
                                    value: "palettes"
                                  })
                            ],
                            className: "p-4 flex flex-row items-start gap-2"
                          }),
                      className: "sidebar flex bg-gray-950 w-80"
                    })
              ],
              className: "bg-gray-900 min-h-screen text-white flex flex-row items-stretch"
            });
}

var make = App;

export {
  make ,
}
/*  Not a pure module */
