// Generated by ReScript, PLEASE EDIT WITH CARE

import * as State from "./State.res.mjs";
import * as ColorWheel from "./ColorWheel.res.mjs";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as ColorHandles from "./ColorHandles.res.mjs";
import * as Core__Option from "@rescript/core/src/Core__Option.res.mjs";
import * as BrightnessSlider from "./BrightnessSlider.res.mjs";
import * as JsxRuntime from "preact/jsx-runtime";

function App(props) {
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsxs("main", {
                      children: [
                        JsxRuntime.jsx("div", {
                              children: JsxRuntime.jsx("ul", {
                                    children: State.colorsSignal.value.map(function (color, i) {
                                          return JsxRuntime.jsxs("li", {
                                                      children: [
                                                        "#" + color.hex,
                                                        JsxRuntime.jsx("div", {
                                                              className: "flex flex-col items-center justify-end rounded-lg border border-white w-full h-[16rem]",
                                                              style: {
                                                                backgroundColor: "#" + color.hex
                                                              }
                                                            })
                                                      ],
                                                      className: "flex flex-col items-center justify-stretch gap-2"
                                                    }, i.toString());
                                        }),
                                    className: "h-full grid grid-cols-5 gap-4"
                                  }),
                              className: "color-list bg-gray-950/40 p-8"
                            }),
                        JsxRuntime.jsxs("div", {
                              children: [
                                JsxRuntime.jsx(ColorHandles.make, {
                                      children: JsxRuntime.jsx(ColorWheel.make, {})
                                    }),
                                JsxRuntime.jsx(BrightnessSlider.make, {})
                              ],
                              className: "color-wheel p-16 flex flex-row justify-center items-center gap-8"
                            }),
                        JsxRuntime.jsxs("div", {
                              children: [
                                JsxRuntime.jsx("button", {
                                      children: "Custom"
                                    }),
                                JsxRuntime.jsx("button", {
                                      children: "Monochromatic"
                                    }),
                                JsxRuntime.jsx("button", {
                                      children: "Analogous"
                                    }),
                                JsxRuntime.jsx("button", {
                                      children: "Complementary"
                                    }),
                                JsxRuntime.jsx("button", {
                                      children: "Split Complementary"
                                    }),
                                JsxRuntime.jsx("button", {
                                      children: "Triad"
                                    }),
                                JsxRuntime.jsx("button", {
                                      children: "Quads"
                                    })
                              ],
                              className: "flex flex-row justify-center gap-2"
                            })
                      ],
                      className: "flex flex-col flex-grow"
                    }),
                JsxRuntime.jsxs("aside", {
                      children: [
                        JsxRuntime.jsxs("nav", {
                              children: [
                                JsxRuntime.jsx("button", {
                                      children: "inspector",
                                      value: "properties"
                                    }),
                                JsxRuntime.jsx("button", {
                                      children: "palettes",
                                      value: "palettes"
                                    })
                              ],
                              className: "p-8 flex flex-row items-start gap-2"
                            }),
                        JsxRuntime.jsx("section", {
                              children: JsxRuntime.jsxs("form", {
                                    children: [
                                      JsxRuntime.jsxs("div", {
                                            children: [
                                              JsxRuntime.jsx("label", {
                                                    children: "Red",
                                                    className: "w-20",
                                                    htmlFor: "id_props_red"
                                                  }),
                                              JsxRuntime.jsx("input", {
                                                    className: "w-10 bg-gray-800 text-right px-2",
                                                    id: "id_props_red",
                                                    type: "text",
                                                    value: "50"
                                                  }),
                                              JsxRuntime.jsx("input", {
                                                    className: "w-full",
                                                    max: "255",
                                                    min: "0",
                                                    type: "range",
                                                    value: "50"
                                                  })
                                            ],
                                            className: "flex flex-row gap-2"
                                          }),
                                      JsxRuntime.jsxs("div", {
                                            children: [
                                              JsxRuntime.jsx("label", {
                                                    children: "Green",
                                                    className: "w-20",
                                                    htmlFor: "id_props_green"
                                                  }),
                                              JsxRuntime.jsx("input", {
                                                    className: "w-10 bg-gray-800 text-right px-2",
                                                    id: "id_props_green",
                                                    type: "text",
                                                    value: "50"
                                                  }),
                                              JsxRuntime.jsx("input", {
                                                    className: "w-full",
                                                    max: "255",
                                                    min: "0",
                                                    type: "range",
                                                    value: "50"
                                                  })
                                            ],
                                            className: "flex flex-row gap-2"
                                          }),
                                      JsxRuntime.jsxs("div", {
                                            children: [
                                              JsxRuntime.jsx("label", {
                                                    children: "Blue",
                                                    className: "w-20",
                                                    htmlFor: "id_props_blue"
                                                  }),
                                              JsxRuntime.jsx("input", {
                                                    className: "w-10 bg-gray-800 text-right px-2",
                                                    id: "id_props_blue",
                                                    type: "text",
                                                    value: "50"
                                                  }),
                                              JsxRuntime.jsx("input", {
                                                    className: "w-full",
                                                    max: "255",
                                                    min: "0",
                                                    type: "range",
                                                    value: "50"
                                                  })
                                            ],
                                            className: "flex flex-row gap-2 mb-4"
                                          }),
                                      JsxRuntime.jsxs("div", {
                                            children: [
                                              JsxRuntime.jsx("label", {
                                                    children: "Hue",
                                                    className: "w-20",
                                                    htmlFor: "id_props_hue"
                                                  }),
                                              JsxRuntime.jsx("input", {
                                                    className: "w-10 bg-gray-800 text-right px-2",
                                                    id: "id_props_hue",
                                                    type: "text",
                                                    value: "50"
                                                  }),
                                              JsxRuntime.jsx("input", {
                                                    className: "w-full",
                                                    max: "360",
                                                    min: "0",
                                                    type: "range",
                                                    value: "50"
                                                  })
                                            ],
                                            className: "flex flex-row gap-2"
                                          }),
                                      JsxRuntime.jsxs("div", {
                                            children: [
                                              JsxRuntime.jsx("label", {
                                                    children: "Sat",
                                                    className: "w-20",
                                                    htmlFor: "id_props_saturation"
                                                  }),
                                              JsxRuntime.jsx("input", {
                                                    className: "w-10 bg-gray-800 text-right px-2",
                                                    id: "id_props_saturation",
                                                    type: "text",
                                                    value: "50"
                                                  }),
                                              JsxRuntime.jsx("input", {
                                                    className: "w-full",
                                                    max: "100",
                                                    min: "0",
                                                    type: "range",
                                                    value: "50"
                                                  })
                                            ],
                                            className: "flex flex-row gap-2"
                                          }),
                                      JsxRuntime.jsxs("div", {
                                            children: [
                                              JsxRuntime.jsx("label", {
                                                    children: "Light",
                                                    className: "w-20",
                                                    htmlFor: "id_props_brightness"
                                                  }),
                                              JsxRuntime.jsx("input", {
                                                    className: "w-10 bg-gray-800 text-right px-2",
                                                    id: "id_props_brightness",
                                                    type: "text",
                                                    value: "50"
                                                  }),
                                              JsxRuntime.jsx("input", {
                                                    className: "w-full",
                                                    max: "100",
                                                    min: "0",
                                                    type: "range",
                                                    value: "50"
                                                  })
                                            ],
                                            className: "flex flex-row gap-2 mb-4"
                                          }),
                                      JsxRuntime.jsxs("div", {
                                            children: [
                                              JsxRuntime.jsx("label", {
                                                    children: "Hex",
                                                    className: "w-20",
                                                    htmlFor: "id_props_hex"
                                                  }),
                                              JsxRuntime.jsx("input", {
                                                    className: "w-24 bg-gray-800 text-right px-2 font-mono",
                                                    id: "id_props_hex",
                                                    type: "text",
                                                    value: State.getSelectedColor().hex,
                                                    onInput: (function (e) {
                                                        State.setSelectedColor({
                                                              TAG: "Hex",
                                                              _0: Core__Option.getOr(Caml_option.nullable_to_opt(e.currentTarget.value), "0e0e0e")
                                                            });
                                                      })
                                                  })
                                            ],
                                            className: "flex flex-row justify-between gap-2 mb-4"
                                          })
                                    ],
                                    className: "p-8 flex flex-col gap-2"
                                  })
                            }),
                        JsxRuntime.jsxs("section", {
                              children: [
                                JsxRuntime.jsx("button", {
                                      children: "Insert Swatch Before"
                                    }),
                                JsxRuntime.jsx("button", {
                                      children: "Insert Swatch After"
                                    }),
                                JsxRuntime.jsx("button", {
                                      children: "Delete Swatch"
                                    })
                              ],
                              className: "flex flex-col gap-2 justify-center"
                            })
                      ],
                      className: "sidebar bg-gray-950 w-96 flex flex-col gap-4"
                    })
              ],
              className: "bg-gray-900 min-h-screen text-white flex flex-row items-stretch"
            });
}

var make = App;

export {
  make ,
}
/* State Not a pure module */
