// Generated by ReScript, PLEASE EDIT WITH CARE

import * as State from "./State.res.mjs";
import * as Core__Int from "@rescript/core/src/Core__Int.res.mjs";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as Core__Option from "@rescript/core/src/Core__Option.res.mjs";
import * as JsxRuntime from "preact/jsx-runtime";

function BrightnessSlider(props) {
  var match = State.getSelectedColor();
  return JsxRuntime.jsx("input", {
              className: "w-full h-[32rem]",
              style: {
                appearance: "slider-vertical"
              },
              max: "100.00",
              min: "0",
              name: "brightness",
              step: "any",
              type: "range",
              value: match.hsv.v.toString(),
              onInput: (function (e) {
                  State.setSelectedColor({
                        TAG: "V",
                        _0: Core__Option.getOr(Core__Option.flatMap(Caml_option.nullable_to_opt(e.currentTarget.value), (function (__x) {
                                    return Core__Int.fromString(__x, 10);
                                  })), 0)
                      });
                }),
              orient: "vertical"
            });
}

var make = BrightnessSlider;

export {
  make ,
}
/* State Not a pure module */
