// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as Hooks from "preact/hooks";
import * as JsxRuntime from "preact/jsx-runtime";

var colors = [
  "red",
  "magenta",
  "blue",
  "cyan",
  "green",
  "yellow",
  "orange",
  "red"
];

function circle(ctx, fill) {
  ctx.beginPath();
  ctx.arc(300, 300, 300, 0.0, 2.0 * Math.PI);
  ctx.fillStyle = fill;
  ctx.fill();
  ctx.closePath();
}

function ColorWheel(props) {
  var canvasRef = Hooks.useRef(null);
  var logRef = function (param) {
    var canvas = canvasRef.current;
    if (!(canvas === null || canvas === undefined)) {
      var ctx = canvas.getContext("2d");
      var conicGradient = ctx.createConicGradient(0, 300, 300);
      var totalColors = colors.length;
      var interval = 1.0 / (totalColors - 1 | 0);
      colors.forEach(function (color, index) {
            var offset = index * interval;
            conicGradient.addColorStop(offset, color);
          });
      circle(ctx, conicGradient);
      var radialGradient = ctx.createRadialGradient(300, 300, 5, 300, 300, 300);
      radialGradient.addColorStop(0.0, "white");
      radialGradient.addColorStop(1.0, "rgba(255, 255, 255, 0");
      return circle(ctx, radialGradient);
    }
    if (canvas === null) {
      console.log("canvas is not set yet");
      return ;
    }
    console.log("canvas is not set yet");
  };
  Hooks.useEffect((function () {
          logRef();
        }), []);
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx("canvas", {
                      ref: Caml_option.some(canvasRef),
                      className: "relative z-20",
                      height: "600",
                      width: "600"
                    }),
                JsxRuntime.jsx("svg", {
                      children: JsxRuntime.jsx("circle", {
                            cx: "320",
                            cy: "320",
                            fill: "rgba(0, 0, 0, 0.25)",
                            r: "320",
                            strokeWidth: "20"
                          }),
                      className: "absolute left-0 top-0 z-10 transform -translate-x-5 -translate-y-5",
                      height: "640",
                      width: "640",
                      viewBox: "0 0 640 640"
                    })
              ],
              className: "relative"
            });
}

var make = ColorWheel;

export {
  make ,
}
/* preact/hooks Not a pure module */
