// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Color from "./Color.res.mjs";
import * as State from "./State.res.mjs";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as Hooks from "preact/hooks";
import * as JsxRuntime from "preact/jsx-runtime";

var colors = [
  360,
  300,
  240,
  180,
  120,
  60,
  0
];

function circle(ctx, fill) {
  ctx.beginPath();
  ctx.arc(300, 300, 300, 0.0, 2.0 * Math.PI);
  ctx.fillStyle = fill;
  ctx.fill();
  ctx.closePath();
}

function drawColorWheel(canvas, hsv) {
  var ctx = canvas.getContext("2d");
  ctx.reset();
  var conicGradient = ctx.createConicGradient(0, 300, 300);
  var totalColors = colors.length;
  var interval = 1.0 / (totalColors - 1 | 0);
  colors.forEach(function (hue, index) {
        var offset = index * interval;
        var match = Color.HSV.toHSL([
              hue,
              100,
              hsv.v
            ]);
        var h$p = match[0].toString();
        var s$p = match[1].toString();
        var l$p = match[2].toString();
        var color = "hsl(" + h$p + " " + s$p + "% " + l$p + "%)";
        conicGradient.addColorStop(offset, color);
      });
  circle(ctx, conicGradient);
  var radialGradient = ctx.createRadialGradient(300, 300, 5, 300, 300, 300);
  radialGradient.addColorStop(0.0, "white");
  radialGradient.addColorStop(1.0, "rgba(255, 255, 255, 0");
  circle(ctx, radialGradient);
}

function ColorWheel(props) {
  var canvasRef = Hooks.useRef(null);
  var match = State.getSelectedColor();
  var hsv = match.hsv;
  var logRef = function (hsv) {
    var canvas = canvasRef.current;
    if (canvas === null || canvas === undefined) {
      if (canvas === null) {
        console.log("canvas is not set yet");
        return ;
      }
      console.log("canvas is not set yet");
      return ;
    } else {
      drawColorWheel(canvas, hsv);
      State.canvasSignal.value = Caml_option.some(canvas);
      return ;
    }
  };
  Hooks.useEffect((function () {
          logRef(hsv);
        }), [
        hsv.h,
        hsv.s,
        hsv.v
      ]);
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx("canvas", {
                      ref: Caml_option.some(canvasRef),
                      className: "relative z-20",
                      id: "color-wheel",
                      height: "600",
                      width: "600"
                    }),
                JsxRuntime.jsx("svg", {
                      children: JsxRuntime.jsx("circle", {
                            cx: "320",
                            cy: "320",
                            fill: "rgba(0, 0, 0, 0.25)",
                            r: "320",
                            strokeWidth: "20"
                          }),
                      className: "absolute left-0 top-0 z-10 transform -translate-x-5 -translate-y-5",
                      height: "640",
                      width: "640",
                      viewBox: "0 0 640 640"
                    })
              ],
              className: "relative"
            });
}

var make = ColorWheel;

export {
  make ,
}
/* State Not a pure module */
