// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as Hooks from "preact/hooks";
import * as JsxRuntime from "preact/jsx-runtime";

var colors = [
  "red",
  "orange",
  "yellow",
  "green",
  "cyan",
  "blue",
  "magenta",
  "red"
];

function ColorWheel(props) {
  var canvasRef = Hooks.useRef(null);
  var logRef = function (param) {
    var canvas = canvasRef.current;
    if (!(canvas === null || canvas === undefined)) {
      var ctx = canvas.getContext("2d");
      var gradient = ctx.createConicGradient(0, 300, 300);
      var totalColors = colors.length;
      var interval = 1.0 / totalColors;
      colors.forEach(function (color, index) {
            var offset = index * interval;
            gradient.addColorStop(offset, color);
          });
      ctx.beginPath();
      ctx.arc(300, 300, 300, 0.0, 2.0 * Math.PI);
      ctx.closePath();
      ctx.fillStyle = {
        NAME: "gradient",
        VAL: gradient
      };
      ctx.fill();
      return ;
    }
    if (canvas === null) {
      console.log("canvas is not set yet");
      return ;
    }
    console.log("canvas is not set yet");
  };
  Hooks.useEffect((function () {
          logRef();
        }), []);
  return JsxRuntime.jsx(JsxRuntime.Fragment, {
              children: Caml_option.some(JsxRuntime.jsx("canvas", {
                        ref: Caml_option.some(canvasRef),
                        height: "600",
                        width: "600"
                      }))
            });
}

var make = ColorWheel;

export {
  make ,
}
/* preact/hooks Not a pure module */
