// Generated by ReScript, PLEASE EDIT WITH CARE


var Signal = {};

var $$AbortController = {
  Signal: Signal
};

var $$Event = {};

var $$MouseEvent = {};

var $$Document = {};

var $$Window = {};

export {
  $$AbortController ,
  $$Event ,
  $$MouseEvent ,
  $$Document ,
  $$Window ,
}
/* No side effect */
