// Generated by ReScript, PLEASE EDIT WITH CARE

import * as State from "./State.res.mjs";
import * as Core__Int from "@rescript/core/src/Core__Int.res.mjs";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as Core__Option from "@rescript/core/src/Core__Option.res.mjs";
import * as Hooks from "preact/hooks";
import * as Signals from "@preact/signals";
import * as JsxRuntime from "preact/jsx-runtime";

function SidebarSlider(props) {
  var __max = props.max;
  var __min = props.min;
  var __className = props.className;
  var get = props.get;
  var set = props.set;
  var className = __className !== undefined ? __className : "";
  var min = __min !== undefined ? __min : "0";
  var max = __max !== undefined ? __max : "100";
  var id = "id_props_" + props.id;
  var valueSignal = Signals.useComputed(function () {
        var color = State.getSelectedColor();
        return get(color).toString();
      });
  var value = valueSignal.value;
  var onInput = Hooks.useCallback((function ($$event) {
          var value = Core__Option.flatMap(Caml_option.nullable_to_opt($$event.currentTarget.value), (function (str) {
                  return Core__Int.fromString(str, undefined);
                }));
          if (value !== undefined) {
            return State.setSelectedColor(set(value));
          }
          
        }), []);
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx("label", {
                      children: props.label,
                      className: "w-20",
                      htmlFor: id
                    }),
                JsxRuntime.jsx("input", {
                      className: "w-10 bg-gray-800 text-right px-1",
                      id: id,
                      type: "text",
                      value: value,
                      onInput: onInput
                    }),
                JsxRuntime.jsx("input", {
                      className: "w-full",
                      max: max,
                      min: min,
                      type: "range",
                      value: value,
                      onInput: onInput
                    })
              ],
              className: "flex flex-row gap-2 " + (
                className.length > 0 ? " " + className : ""
              )
            });
}

var make = SidebarSlider;

export {
  make ,
}
/* State Not a pure module */
