// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Core__Option from "@rescript/core/src/Core__Option.res.mjs";
import * as Signals from "@preact/signals";

var stateSignal = Signals.signal({
      selectedColor: 0,
      colors: [
        "000000",
        "000000",
        "000000",
        "000000",
        "000000"
      ]
    });

function getSelectedColor() {
  var match = stateSignal.value;
  return Core__Option.getOr(match.colors[match.selectedColor], "000000");
}

function setSelectedColor(color) {
  var state = stateSignal.value;
  var updatedColors = state.colors.toSpliced(state.selectedColor, 1, color);
  stateSignal.value = {
    selectedColor: state.selectedColor,
    colors: updatedColors
  };
}

var colorsSignal = Signals.computed(function () {
      return stateSignal.value.colors;
    });

export {
  stateSignal ,
  getSelectedColor ,
  setSelectedColor ,
  colorsSignal ,
}
/* stateSignal Not a pure module */
