// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Color from "./Color.res.mjs";
import * as Core__Option from "@rescript/core/src/Core__Option.res.mjs";
import * as Signals from "@preact/signals";

var stateSignal = Signals.signal({
      selectedColor: 0,
      colors: [
        {
          TAG: "HSV",
          _0: 360,
          _1: 100,
          _2: 100
        },
        {
          TAG: "HSV",
          _0: 0,
          _1: 0,
          _2: 0
        },
        {
          TAG: "HSV",
          _0: 0,
          _1: 0,
          _2: 0
        },
        {
          TAG: "HSV",
          _0: 0,
          _1: 0,
          _2: 0
        },
        {
          TAG: "HSV",
          _0: 0,
          _1: 0,
          _2: 0
        }
      ]
    });

function parseColorState(color) {
  switch (color.TAG) {
    case "Hex" :
        var hex = color._0;
        var rgb = Color.Hex.toRGB(hex);
        var match = Color.RGB.toHSV(rgb);
        return {
                rgb: {
                  r: rgb[0],
                  g: rgb[1],
                  b: rgb[2]
                },
                hsv: {
                  h: match[0],
                  s: match[1],
                  v: match[2]
                },
                hex: hex
              };
    case "RGB" :
        var b = color._2;
        var g = color._1;
        var r = color._0;
        var rgb$1 = [
          r,
          g,
          b
        ];
        var hex$1 = Color.RGB.toHex(rgb$1, undefined);
        var match$1 = Color.RGB.toHSV(rgb$1);
        return {
                rgb: {
                  r: r,
                  g: g,
                  b: b
                },
                hsv: {
                  h: match$1[0],
                  s: match$1[1],
                  v: match$1[2]
                },
                hex: hex$1
              };
    case "HSV" :
        var v = color._2;
        var s = color._1;
        var h = color._0;
        var hsv = [
          h,
          s,
          v
        ];
        var rgb$2 = Color.HSV.toRGB(hsv);
        var hex$2 = Color.RGB.toHex(rgb$2, undefined);
        return {
                rgb: {
                  r: rgb$2[0],
                  g: rgb$2[1],
                  b: rgb$2[2]
                },
                hsv: {
                  h: h,
                  s: s,
                  v: v
                },
                hex: hex$2
              };
    
  }
}

var colorsSignal = Signals.computed(function () {
      var match = stateSignal.value;
      return match.colors.map(parseColorState);
    });

var selectedColorSignal = Signals.computed(function () {
      var match = stateSignal.value;
      var colors = colorsSignal.value;
      return Core__Option.getOr(colors[match.selectedColor], {
                  rgb: {
                    r: 0,
                    g: 0,
                    b: 0
                  },
                  hsv: {
                    h: 0,
                    s: 0,
                    v: 0
                  },
                  hex: "000000"
                });
    });

function getSelectedColor() {
  return selectedColorSignal.value;
}

function setSelectedColor(color) {
  var state = stateSignal.value;
  var updatedColors = state.colors.toSpliced(state.selectedColor, 1, color);
  stateSignal.value = {
    selectedColor: state.selectedColor,
    colors: updatedColors
  };
}

function setBrightness(value) {
  var match = selectedColorSignal.value;
  var hsv = match.hsv;
  setSelectedColor({
        TAG: "HSV",
        _0: hsv.h,
        _1: hsv.s,
        _2: value
      });
}

export {
  stateSignal ,
  parseColorState ,
  colorsSignal ,
  selectedColorSignal ,
  getSelectedColor ,
  setSelectedColor ,
  setBrightness ,
}
/* stateSignal Not a pure module */
